### ISSUE TITLE
Optional functionality in wheels

### ISSUE THREAD

**Issue by natefoo** [lincolnloop/pyuwsgi-wheels#1]
Continuing the conversation from unbit/uwsgi#816

@natefoo wrote:
> There's not a great way with the standard PyPA tooling to provide wheels with differing functionality. Some, such as linking libpcre, is probably safe to include in all wheels since it only enables additional functionality but does not otherwise change the behavior of a non-PCRE build. But others, such as linking libyaml, change the normal behavior in incompatible ways. To support both, uWSGI needs a switch to specify "use internal YAML parsing even if built with libyaml," but maybe there is some setuptools `extras_require` trick that can be used here (e.g. for `pip install pyuwsgi[libyaml]`).

@ipmb wrote:
> I'm leaning towards the wheel configuration being opinionated and if you want something different, you can always build your own from the sdist. My current thinking is to bundle zlib, pcre, libyaml, and jansson, but exclude ssl. Would that work for your use case?

These opinionated wheels seem preferable to building a big matrix of feature combinations, and I'm pretty certain there's no way to really do features for dependencies of C extensions like I suggested in PyPI anyway without some major ugliness. It'd be good to document any incompatibilities with a standard `pip install uwsgi` build in the long description.

Is the SSL exclusion to avoid having to rebuild with each OpenSSL vulnerability? FWIW, manylinux does at least install a modern OpenSSL in manylinux1 so you're not using the ancient CentOS 5 version. I don't personally use SSL in uWSGI but we do [include deployer instructions](https://docs.galaxyproject.org/en/latest/admin/scaling.html#listening-and-proxy-options) for simpler setups, and those instructions would be broken without it. That said, most people using our project are just going to proxy uWSGI anyway, but I have no idea how common using SSL directly in uWSGI is outside my project's bubble.

**Comment by ipmb** [comment]
> Is the SSL exclusion to avoid having to rebuild with each OpenSSL vulnerability?

Yes. I don't use it either and I would imagine proxying with HTTPS termination is the common use case.  I figured this is the safest place to start.

I'll add some notes to the project after I talk to @unbit about getting the buildconf dialed in so we do the right thing in the wheels while still allowing users the freedom to build/choose their own.

**Comment by ipmb** [comment]
Just submitted a PR for this information upstream https://github.com/unbit/uwsgi/pull/1878/
