### ISSUE TITLE
pyuwsgi not building on Mac OS 11.0

### ISSUE THREAD

**Issue by jwon** [lincolnloop/pyuwsgi-wheels#14]
When trying to install `pyuwsgi` on MacOS 11.0, I get an error:

```
pyuwsgi-2.0.20-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

Can you please add building wheels for other versions of OS X, not just 10.5?

Thank you!

**Comment by ipmb** [comment]
@jwon are/were you on Apple Silicon (M1/M2)? I suspect this is the case and have an open issue for it here #10
