### ISSUE TITLE
pip install pyuwsgi --no-binary=pyuwsgi throwing error

### ISSUE THREAD

**Issue by dhaparam** [lincolnloop/pyuwsgi-wheels#15]
I have been trying to install `--no-binary=pyuwsgi` to support SSL. But it seems to be throwing an error.

I do not have privilege's to download gcc compilers or update packages. All I have is virtualenv.

The same error throws when I run `pip install uwsgi` and `pip install pyuwsgi --no-binary=pyuwsgi`

**Errror Stack**

 ERROR: Command errored out with exit status 1:
     command: /path/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mojutio_/pyuwsgi_6fd83f7471824b61bae79d5bacdfc8fc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mojutio_/pyuwsgi_6fd83f7471824b61bae79d5bacdfc8fc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tl173oq4/install-record.txt --single-version-externally-managed --compile --install-headers /path/venv/include/site/python3.6/pyuwsgi
         cwd: /tmp/pip-install-mojutio_/pyuwsgi_6fd83f7471824b61bae79d5bacdfc8fc/
    Complete output (152 lines):
    running install
    /path/venv/lib64/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying uwsgidecorators.py -> build/lib.linux-x86_64-3.6
    running build_ext
    using profile: buildconf/pyuwsgi.ini
    detected include path: ['/usr/lib/gcc/x86_64-redhat-linux/8/include', '/usr/local/include', '/usr/include']
    detected CPU cores: 16
    configured CFLAGS: -O2 -I. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -DUWSGI_LOCK_USE_MUTEX -DUWSGI_EVENT_USE_EPOLL -DUWSGI_EVENT_TIMER_USE_TIMERFD -DUWSGI_EVENT_FILEMONITOR_USE_INOTIFY -fPIC -DUWSGI_AS_SHARED_LIBRARY  -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_CAP -DUWSGI_UUID -DUWSGI_VERSION="\"2.0.20\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="20" -DUWSGI_VERSION_REVISION="0" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_JSON -DUWSGI_SSL -I/usr/inc

**Comment by ipmb** [comment]
It looks like the error message is cut off, but I can say that if you want to install without the binary, you'll need the some build libraries like gcc.

If you can get `pip install uwsgi` working, you should be able to do `pip install --no-binary=pyuwsgi pyuwsgi`.

For support getting `uwsgi` installed, please file an issue upstream at https://github.com/unbit/uwsgi/issues
