### ISSUE TITLE
Reloading (`kill -HUP $MASTER_PID`) fails when using a virtualenv - No module named 'pyuwsgi'

### ISSUE THREAD

**Issue by bluetech** [lincolnloop/pyuwsgi-wheels#19]
### Problem

When using the `uwsgi` binary or `pyuwsgi.run()` from this package under a virualenv, reloading a uWSGI process by sending a `SIGHUP` signal to the master process causes the process to crash with the following traceback:

```
Traceback (most recent call last):
  File "/my/venv/bin/uwsgi", line 5, in <module>
    from pyuwsgi import run
ModuleNotFoundError: No module named 'pyuwsgi'
```

### Investigation

The reason this happens is that when the run script is executed after the reload, the `sys.executable` does not point to the venv's python binary, but to the system's python binary. This in turn causes Python's `site.py` to not adjust `sys.prefix`/`sys.exec_prefix`, and to use the system's `site-packages` instead of the venv's. When then causes the `import pyuwsgi` to fail.

I didn't investigate exactly why this happens, I assume it's something inside of uWSGI, which doesn't matter for the regular uWSGI because it doesn't have a run script which imports itself, instead it's just a binary.

For now I work around the problem by using my own run script calling `pyuwsgi.run()`, with this additional snippet before the call:

```py
VIRTUAL_ENV = os.environ['VIRTUAL_ENV']
if sys.prefix != VIRTUAL_ENV:
    import site
    for package in site.getsitepackages():
        try:
            sys.path.remove(package)
        except ValueError:
            pass
    site.addsitepackages(set(sys.path), [VIRTUAL_ENV])
```

This is good enough to get the `pyuwsgi.run()` to work, after which it sets up its own pythonpath/virtualenv so the hack doesn't matter much anymore.

**Comment by bluetech** [comment]
Already reported at https://github.com/unbit/uwsgi/issues/2478.

There, asottile gives a simpler workaround than the snippet above: pass `[..., '--binary-path', sys.executable, ...]` to `pyuwsgi.run()`.

**Comment by ipmb** [comment]
Closing this in favor of https://github.com/unbit/uwsgi/issues/2478. Thanks for the update @bluetech
