### ISSUE TITLE
Non-standard libs can't be bundled in macOS 

### ISSUE THREAD

**Issue by natefoo** [lincolnloop/pyuwsgi-wheels#2]
Continuing the conversation from unbit/uwsgi#816

@natefoo wrote:
> It's not possible to bundle nonstandard libs into the macOS wheel currently (libyaml, libpcre, ...) due to a limitation in delocate described in [matthew-brett/delocate#12 (comment)](https://github.com/matthew-brett/delocate/issues/12#issuecomment-246536098) unless the pyuwsgi shared lib is placed inside a dummy package. It may make more sense to fix delocate rather than pyuwsgi, however.

Fundamentally this is a delocate limitation (it works with auditwheel) and maybe @matthew-brett has some ideas on how feasible implementing support for it would be. I'm motivated to contribute time, if that helps. :smile: 

Alternatively, we can put pyuwsgi into an actual package namespace, I've tried this out in my [pyuwsgi-package](https://github.com/natefoo/uwsgi/tree/pyuwsgi-package) branch and it works (at least enough to execute) for Python 3 but breaks C extension module initialization for Python 2.7. But I've only put about 15 minutes into this, so that's presumably fixable.

**Comment by matthew-brett** [comment]
Yes, it should be easy-ish - if you'd like to help, I'm sure we can get it done in a day or so.

**Comment by natefoo** [comment]
Great, thanks for responding! I'll have a look, then.

**Comment by natefoo** [comment]
Just for future reference, work on it is here: matthew-brett/delocate#39

**Comment by ipmb** [comment]
Hoping this gets resolved upstream soon, but in the meantime, you probably want to build the MacOS pyuwsgi wheels locally (unless you have all the necessary libraries installed) via:

```
pip install --no-binary=pyuwsgi pyuwsgi
```

**Comment by ipmb** [comment]
I setup @natefoo's fork in de3635cf9c1649a5a3e7a56bd7908d93d4900009 and released it on PyPI as `2.0.17.2b4`.
