### ISSUE TITLE
Wheels for Python 3.13

### ISSUE THREAD

**Issue by frenzymadness** [lincolnloop/pyuwsgi-wheels#30]
The final version of Python 3.13 will be out soon. Would it be possible to start building and releasing wheels for 3.13? We have started running our tests with it in the environment where we cannot compile pyuwsgi from sources so that would help us a lot.

**Comment by asottile** [comment]
the current released version doesn't build at all for 3.13 so we'll have to wait for one that does

**Comment by asottile** [comment]
via 2.0.27.post1
